config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resource :profile
  end
  root 'pages#home'
  get '/about' => 'pages#about'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :plan 
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @voter_plan = Plan.find(1)
        @cand_plan = Plan.find(2)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    
    before_action :authenticate_user!
    before_action :only_current_user
    
    def new
        @user = User.find( params[:user_id] )
        @profile = Profile.new
    end
    def create
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile(profile_params)
        if @profile.save
          flash[:success] = "Profile Updated!"
          redirect_to user_path( params[:user_id] )
        else
          render action: :new
        end
    end
    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    def update
        @user = User.find( params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end
    
    private
    
    def profile_params
        
        params.require(:profile).permit(:first_name, :middle_name, :last_name, :phone_number, :user_id, :phone_number, :contact_email, :political_party, :age, :gender, :ethnicity, :Platform, :candidate_for )
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:First_Name, :Last_Name, :Middle_Name, :Username, :Age, :Gender, :Ethnicity, :State, :City_or_Town, :Political_Party, :Running_for_Office_of, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:First_Name, :Last_Name, :Middle_Name, :Username, :Age, :Gender, :Ethnicity, :State, :City_or_Town, :Political_Party, :Running_for_Office_of, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PollingPlace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa fa-users" style="color:white"></i>
      PollingPlace
      <% end %>
      
    </div>
    </div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
    
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right">
      <% if current_user %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
      <% end %>
      </div>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron text-center">
  <p>This is your</p>
  <h1>PollingPlace</h1>
  <h3>This page talks about the site and how to use it.</h3>
</div>

app/views/pages/home.html.erb
<%= link_to "Create your profile!", new_user_profile_path(current_user), class: 'btn btn-primary btn-lg, btn-block' if current_user %>
<div class="jumbotron text-center">
  <p>Welcome to your</p>
  <h1>PollingPlace</h1>
  <h3>A site where Americans can meet Candidates for upcoming Elections.</h3>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="well">
      <h2 class="text-center">Register as a Voter</h2>
      <ul>
        <li>Create Profile</li>
        <li>View Local and National Statistics</li>
        <li>View and "Vote" Local Bills Measures and Proposals</li>
        <li>View and "Vote" for Candidates</li>
      </ul>
      <br/>
      <br/>
      <br/>
      <%= link_to "Register as Voter", new_user_registration_path(plan: @voter_plan.id), class: "btn btn-lg btn-primary" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well">
      <h2 class="text-center">Register as a Candidate</h2>
      <ul>
        <li>Create Profile</li>
        <li>View Polling Statistics</li>
        <li>View Demographic Statistics</li>
        <li>Post Messages</li>
        <li>Post Pics and Videos</li>
        <li>Respond to Questions and Comments</li>
        <li>View News Articles and Videos about Your Campaign</li>
      </ul>
      <%= link_to "Register as Candidate", new_user_registration_path(plan: @cand_plan.id), class: "btn btn-lg btn-danger" %>
    </div>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :middle_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.select :age, (18..100), {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :gender %>
    <%= f.select :gender, ['male', 'female'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :ethnicity %>
    <%= f.select :ethnicity, ['White', 'Hispanic or Latino', 'Asian', 'Black or African american', 'Native Hawaiian or other Pacific Islander', 'American Indian or Alaska Native'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :political_party %>
    <%= f.select :political_party, ['Democrat', 'Republican', 'Independent', 'Libertarian', 'Green', 'Constitution'], {}, class: 'form-control' %>
  </div>
   <% if current_user.plan_id == 2 %>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :candidate_for %>
          <%= f.text_field :candidate_for, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Platform %>
          <%= f.text_area :Platform, class: 'form-control' %>
        </div>
    <% end %>
 
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Profile</h1>
    <p class="text-center">Join the Polling Place and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <% if current_user.plan_id == 2 %>
            <h1 class="text-center">Create Your Candidate Profile</h1>
            <p class="text-center">Join the next stage of American Politics!</p>
        <% else %>
            <h1 class="text-center">Create Your Voter Profile</h1>
            <p class="text-center">Join the next stage of American Politics!</p>
        <% end %>
        <div class="well">
            <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :middle_name %>
          <%= f.text_field :middle_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :age %>
          <%= f.select :age, (18..100), {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :gender %>
          <%= f.select :gender, ['male', 'female'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :ethnicity %>
          <%= f.select :ethnicity, ['White', 'Hispanic or Latino', 'Asian', 'Black or African american', 'Native Hawaiian or other Pacific Islander', 'American Indian or Alaska Native'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :political_party %>
          <%= f.select :political_party, ['Democrat', 'Republican', 'Independent', 'Libertarian', 'Green', 'Constitution'], {}, class: 'form-control' %>
        </div>
        <% if current_user.plan_id == 2 %>
            <div class="form-group">
              <%= f.label :contact_email %>
              <%= f.text_field :contact_email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :candidate_for %>
              <%= f.text_field :candidate_for, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :Platform %>
              <%= f.text_area :Platform, class: 'form-control' %>
            </div>
        <% end %>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="well">
            
            <%= @user.profile.first_name %> <%= @user.profile.last_name %> <br />
            <%= @user.profile.political_party %> <br />
            <%= @user.profile.gender %> <br />
            <%= @user.profile.ethnicity %> <br />
            
            
        </div> 
    </div>
</div>